#!/usr/bin/env bash
# scripts/recall-mcp.sh — MCP stdio wrapper for the recall retrieval service.
# Auto-generated by recall-portal for tenant btrzupek / repo stm-vuln-app.
#
# Two modes, selected by whether RECALL_URL is set in env:
#
#   Deployed mode   (RECALL_URL set)    — forwards MCP calls over HTTPS to the
#                   running recall service. RECALL_QUERY_TOKEN is remapped to
#                   RECALL_SERVICE_TOKEN before exec'ing RECALL_MCP_BIN.
#
#   Local-stack mode (RECALL_URL unset) — reads connection details + service
#                   token from the state dir written by local-stack-up.sh.

set -euo pipefail

# Consumer identity for this repo.
TENANT_ID="btrzupek"
REPO_ID="stm-vuln-app"

MCP_BIN="${RECALL_MCP_BIN:-recall-mcp-server}"
STATE_DIR="${RECALL_LOCAL_STATE_DIR:-${TMPDIR:-/tmp}/recall-local}"

if [[ -n "${RECALL_URL:-}" ]]; then
    # ── Deployed mode ──────────────────────────────────────────────────────
    repo_token_file="${HOME}/.config/recall/query-token-${REPO_ID}"
    if [[ -r "${repo_token_file}" ]]; then
        RECALL_QUERY_TOKEN="$(cat "${repo_token_file}")"
    fi
    if [[ -z "${RECALL_QUERY_TOKEN:-}" ]]; then
        printf 'recall-mcp: no token for repo "%s" — write %s or set RECALL_QUERY_TOKEN\n' \
            "${REPO_ID}" "${repo_token_file}" >&2
        exit 1
    fi
    export RECALL_SERVICE_TOKEN="${RECALL_QUERY_TOKEN}"
    export RECALL_TENANT_ID="${TENANT_ID}"
    export RECALL_REPO_ID="${REPO_ID}"
    export RECALL_CALLER_KIND="${RECALL_CALLER_KIND:-human}"
    exec "${MCP_BIN}"
else
    # ── Local-stack mode ───────────────────────────────────────────────────
    env_file="${STATE_DIR}/env"
    token_file="${STATE_DIR}/service-token"

    if [[ ! -f "${env_file}" ]]; then
        printf 'recall-mcp: local stack not running (no state at %s)\n' "${STATE_DIR}" >&2
        exit 1
    fi
    if [[ ! -f "${token_file}" ]]; then
        printf 'recall-mcp: service token not found at %s\n' "${token_file}" >&2
        exit 1
    fi

    # shellcheck source=/dev/null
    source "${env_file}"
    RECALL_SERVICE_TOKEN="$(cat "${token_file}")"
    export RECALL_SERVICE_TOKEN
    export RECALL_CALLER_KIND="${RECALL_CALLER_KIND:-human}"
    exec "${MCP_BIN}"
fi
