#!/usr/bin/env bash
# scripts/recall-setup.sh — one-command local dev setup for recall.
#
# Auto-generated by recall-portal for btrzupek/stm-vuln-app.
# Run from the repo root after merging the recall onboarding PR.

set -euo pipefail

TENANT_ID="btrzupek"
REPO_ID="stm-vuln-app"
RECALL_URL="https://recall-dev-agitk5jfpq-uc.a.run.app"
BINARY_BASE="https://storage.googleapis.com/recall-mcp-binaries/latest-staging"

# ── Detect OS + arch ─────────────────────────────────────────────────────
os_raw=$(uname -s)
arch_raw=$(uname -m)
case "$os_raw" in
  Darwin) os=darwin ;;
  Linux)  os=linux ;;
  *) echo "recall-setup: unsupported OS: $os_raw" >&2; exit 1 ;;
esac
case "$arch_raw" in
  arm64|aarch64) arch=arm64 ;;
  x86_64|amd64)  arch=amd64 ;;
  *) echo "recall-setup: unsupported arch: $arch_raw" >&2; exit 1 ;;
esac
# Currently published binaries: darwin-arm64, darwin-amd64, linux-amd64.
if [[ "$os" == "linux" && "$arch" == "arm64" ]]; then
  echo "recall-setup: linux/arm64 binary is not published yet; please file an issue." >&2
  exit 1
fi
platform="${os}-${arch}"
echo "✓ detected ${platform}"

# ── Download binary ──────────────────────────────────────────────────────
# All three platforms (linux-amd64, darwin-arm64, darwin-amd64) are
# published anonymously to the public GCS bucket on every prod promotion
# of recall. No auth, no gh CLI needed.
mkdir -p ./bin
bin_path="./bin/recall-mcp-server"
url="${BINARY_BASE}/recall-mcp-server-${platform}"
if ! curl -fsSL --output "$bin_path" "$url"; then
  echo "recall-setup: download failed: ${url}" >&2
  echo "If you're on an unsupported platform, file an issue at https://github.com/digicert/recall-portal." >&2
  exit 1
fi
curl -fsSL --output "${bin_path}.sha256" "${url}.sha256"
echo "✓ downloaded ${platform} from ${BINARY_BASE}"

# Verify checksum (the published .sha256 is "<hex>  <filename>" format).
expected=$(awk '{print $1}' "${bin_path}.sha256")
actual=$(shasum -a 256 "$bin_path" | awk '{print $1}')
if [[ "$expected" != "$actual" ]]; then
  echo "recall-setup: sha256 mismatch — refusing to install" >&2
  echo "  expected: $expected" >&2
  echo "  got:      $actual" >&2
  exit 1
fi
chmod +x "$bin_path"
chmod +x scripts/recall-mcp.sh
echo "✓ verified ${bin_path}"

if [[ "$expected" != "" ]]; then :; fi  # silences shellcheck on conditionals above

# ── Token: env var wins; otherwise prompt ────────────────────────────────
mkdir -p "${HOME}/.config/recall"
token_file="${HOME}/.config/recall/query-token-${REPO_ID}"
if [[ -n "${RECALL_QUERY_TOKEN:-}" ]]; then
  printf '%s' "$RECALL_QUERY_TOKEN" > "$token_file"
  chmod 600 "$token_file"
  echo "✓ token from RECALL_QUERY_TOKEN env → ${token_file}"
else
  printf 'Paste your RECALL_QUERY_TOKEN (input hidden): '
  IFS= read -rs token
  echo
  if [[ -z "$token" ]]; then
    echo "recall-setup: empty token, aborting" >&2
    exit 1
  fi
  printf '%s' "$token" > "$token_file"
  chmod 600 "$token_file"
  echo "✓ token written to ${token_file}"
fi

# ── Project-local env file ───────────────────────────────────────────────
cat > .env.recall <<ENVEOF
# Generated by recall-setup.sh. Source this from your shell, or use direnv.
export RECALL_URL="${RECALL_URL}"
export RECALL_MCP_BIN="$(pwd)/bin/recall-mcp-server"
export RECALL_REPO_PATH="$(pwd)"
ENVEOF
echo "✓ wrote .env.recall"

# ── .gitignore hygiene ───────────────────────────────────────────────────
touch .gitignore
for line in ".env.recall" "/bin/" "/bin/recall-mcp-server" "/bin/recall-mcp-server.sha256"; do
  if ! grep -Fxq "$line" .gitignore; then
    echo "$line" >> .gitignore
    echo "✓ added ${line} to .gitignore"
  fi
done

cat <<'TIPEOF'

All set. To activate in your current shell:

    source .env.recall

(or run "direnv allow" if you use direnv).

Then open Claude Code in this directory and try:

    is this repo using recall? what files reference jwt?

If Claude Code says recall isn't loaded, check that .mcp.json exists and
that RECALL_QUERY_TOKEN / RECALL_MCP_BIN are visible to the spawned shell.
TIPEOF
