name: Generate SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    # Updated to v4
    
    - name: Generate SBOM
      uses: CycloneDX/gh-python-generate-sbom@v1
      with:
        input: requirements.txt  # For Python projects
        output: bom.xml
        format: xml
    
    - name: Upload SBOM
      uses: actions/upload-artifact@v4    # Updated to v4
      with:
        name: sbom
        path: bom.xml
        retention-days: 90    # Optional: specify how long to keep the artifact
