name: Vulnerability Scanner

on:
  push:
    branches:
      - main

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run vulnerability scanner
        uses: ./.github/actions/vulnerability-scanner-plugin
        with:
          scanner-token: ${{ secrets.SCANNER_TOKEN }}
          scanner-name: ${{ secrets.SCANNER_NAME }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

